# Generated by Django 4.0.1 on 2022-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the client.', unique=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('views', models.ManyToManyField(related_name='post_views', to='posts.IPAddress')),
            ],
            options={
                'ordering': ['post_created'],
            },
        ),
    ]
